### PR TITLE
CI fixes: ensure podman-pugins is installed on Fedora

### PR DESCRIPTION
**Pull request by gicmo**
Also temporarily switch over to a different repo for the brew packages since the current one is in a broken state.

### CODE REVIEW

**Review by larskarlitski — APPROVED** [review]
:face_with_head_bandage: 

Thanks!

**Review by larskarlitski — APPROVED** [review]
Oh dear. Thanks again.

**Review by teg — APPROVED** [review]
Makes sense to me, but did the repos get fixed in the meantime? (`podman` in Fedora dropped the dependency, so adding that explicitly is correct now)

**Comment by gicmo** [comment]
> Makes sense to me, but did the repos get fixed in the meantime? (`podman` in Fedora dropped the dependency, so adding that explicitly is correct now)

They should be indeed, I have dropped the EPEL-8 commit.

**Review by larskarlitski — APPROVED** [review]

**Pull request merged**
