### PR TITLE
Test and CI maintenance

### PR DESCRIPTION
**Pull request by ondrejbudai**
- Remove Fedora 34 from CI
- Add Fedora 32 to CI
- Use Fedora 34 instead of Fedora 32 in tests
- Speed up `mockbuild`

### CODE REVIEW

**Comment by gicmo** [comment]
> 2 malformed task: free -> FAILED: GenericError: Failed to create the compose request: {"message":"Unsupported distribution: fedora-34"}

I guess we need to update composer to a version that supports F34?

**Comment by ondrejbudai** [comment]
Yes, this is blocked on https://bodhi.fedoraproject.org/updates/FEDORA-2021-5a4b58555d

**Review by gicmo — DISMISSED** [review]
❤️ Thanks so much for this!

**Comment by ondrejbudai** [comment]
This is now ready! \o/

**Review by gicmo — APPROVED** [review]
❤️

**Pull request merged**
