### PR TITLE
CI: Update workers fleet (COMPOSER-1997)

### PR DESCRIPTION
**Pull request by elkoniu**
By default CI is running on RHEL 8, F36 and F37 workers. This commit adds Fedora 38 to the workers list
and removes deprecated Fedora 36

### CODE REVIEW

**Comment by ochosi** [comment]
I think you may also have to update the `terraform` and `deploy.sh` files in the schutzbot directory. See e.g. https://github.com/osbuild/koji-osbuild/commit/32d9826e1e882ad1ccc7c44cf6922a265116b515

**Comment by elkoniu** [comment]
> Neato! <3 I think you may also have to update the `terraform` and `deploy.sh` files in the schutzbot directory. See e.g. [32d9826](https://github.com/osbuild/koji-osbuild/commit/32d9826e1e882ad1ccc7c44cf6922a265116b515)

Looks like you are right. I will check result of the CI 1st, then will sync with Tomas on the morning to learn more about those files you mentioned. Thanks \o/

**Comment by elkoniu** [comment]
@ondrejbudai Last time I check (this night) all CI passed apart of RHEL 8.6. Added F38 succeded. I am wondering if it classifies this PR as accepted? I just retriggered RHEL 8.6 for the 3rd time (it fails at timeout at 4h time span).

**Comment by ondrejbudai** [comment]
Ugh, the issue is that the cleanup scripts are never run, because the script just dies (due to `set -e`) after the test returns a non-zero exit code. However, this means that we have a leftover process in background, which unfortunately prevent the job to finish properly. I took the liberty of pushing a commit that hopefully fixes that. My dream is that if the job finishes properly (even though it fails), we should have access to some better logs.

**Comment by elkoniu** [comment]
Thank you for taking a look at this :)

>  I took the liberty of pushing a commit that hopefully fixes that. My dream is that if the job finishes properly (even though it fails), we should have access to some better logs.

So this issue is not related to my change? Shall I just rebase to the latest master and retrigger this PR on top of you changes?

**Comment by elkoniu** [comment]
@ondrejbudai By mistake I have overwritten your fix for env cleanup and killing process leftovers. I tried to recreate your change out of memory and include in my change. Sorry for that.

**Pull request closed without merging**
